### PR TITLE
Allow option for self signed certificates

### PR DESCRIPTION
**Pull request by joaquin-corchero**
When creating tests against urls that have self signed certificates tests fail, the error being returned is  `unable to get local issuer certificate`.

A new option **rejectUnauthorized** can be passed as part of the request object, setting it to false bypasses ssl validations:

`"request":{ ...
          "rejectUnauthorized": false,
...}`

on both, **hooks** and **main** **requests** no error related to certificates should be returned.

### CODE REVIEW

**Comment by joaquin-corchero** [comment]
@darArch can you have a look at the PR?

Thank you

**Comment by darArch** [comment]
This all looks good, could you do me a favour and merge master back in to see if my changes let the Travis build run successfully, currently I believe it's using misnamed environment variables in the `docker_publish.sh` file. As soon as we get the build passing I'll get this merged.

**Comment by joaquin-corchero** [comment]
@dararch not in until Monday. Will merge then...

Cheers

**Comment by joaquin-corchero** [comment]
@darArch seems to be having the same behaviour as last week...

**Comment by darArch** [comment]
I'm going to merge this, I suspect the failing build is due to it being a branch rather than master

**Pull request merged**
